"""rename tables

Revision ID: 1d528f17f86e
Revises: 23a423ff02f6
Create Date: 2022-09-26 23:49:47.320528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision = '1d528f17f86e'
down_revision = '23a423ff02f6'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('DROP TABLE public.user CASCADE')
    op.create_table('users',
    sa.Column('id', UUID(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('second_name', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('photo_url', postgresql.INET(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', UUID(), autoincrement=True, nullable=False),
    sa.Column('user_id', UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('files', postgresql.INET(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('price', postgresql.MONEY(), nullable=True),
    sa.Column('type', UUID(), nullable=True),
    sa.Column('executor_id', UUID(), nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.ForeignKeyConstraint(['type'], ['order_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['executors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', postgresql.MONEY(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['executors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.MONEY(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='wallet_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='wallet_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('second_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('order',
    sa.Column('id', UUID(), autoincrement=True, nullable=False),
    sa.Column('user_id', UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('files', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('type', UUID(), autoincrement=False, nullable=True),
    sa.Column('executor_id', UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['user.id'], name='order_executor_id_fkey'),
    sa.ForeignKeyConstraint(['type'], ['order_types.id'], name='order_type_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='order_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_pkey')
    )
    op.drop_table('wallets')
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
