"""ids to uuidlast

Revision ID: 1f8b6facf661
Revises: a3eca0c2a888
Create Date: 2022-12-18 20:55:58.234944

"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8b6facf661'
down_revision = 'a3eca0c2a888'
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.execute('ALTER TABLE executors ALTER COLUMN id type UUID using id::UUID;')
    # op.execute('ALTER TABLE order_types ALTER COLUMN id TYPE UUID')
    # op.execute('ALTER TABLE orders ALTER COLUMN id TYPE UUID')
    # op.execute('ALTER TABLE orders ALTER COLUMN type TYPE UUID')
    # op.execute('ALTER TABLE orders ALTER COLUMN executor_id TYPE UUID')
    # op.execute('ALTER TABLE wallets ALTER COLUMN user_id TYPE UUID')
    # op.execute('ALTER TABLE wallets ALTER COLUMN id TYPE UUID')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
