"""ids to uuid2

Revision ID: a3eca0c2a888
Revises: 6bf9f4e7ea99
Create Date: 2022-12-18 20:53:51.303351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3eca0c2a888'
down_revision = '6bf9f4e7ea99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_types', sa.Column('names', sa.Text(), nullable=True))
    op.add_column('order_types', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('order_types', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_types', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('order_types', 'description')
    op.drop_column('order_types', 'names')
    # ### end Alembic commands ###
